### ISSUE TITLE
Incorrect calculation of rocket's height

### ISSUE THREAD

**Issue by srflp** [Jmack66/PIDtest#2]
Hi,

in this place:
https://github.com/Jmack66/PIDtest/blob/3679f58db174b5901b6c96f59c08ab4f170f515e/PID_Video.py#L113-L114

there should be:
```python3
	def set_y(self):
		self.Rocket.sety(self.y + self.dy * TIME_STEP)
```

because distance = velocity * time

After this fix, you can use default parameters from a website, that I and a couple of my friends wrote. It's an online simulator and we based our PID controller on yours.

online simulator: https://srflp.github.io/pid-rocket/
github: https://github.com/srflp/pid-rocket

With this fix and after setting the parameters to ours, your code outputs same charts as our website.

Thank you for your work!

**Comment by Jmack66** [comment]
Thanks for catching that! i also made the same mistake for dy and changed that but did not catch the same issue on y! 
So glad you found the code useful and were able to use it in your own project :D
